Fix/issue116
GreenByMe/GreenByMe_Server pull request #127
Opened 2020-09-18 14:29 UTC by Livenow14

[api/user/]

2020-09-18 16:25 UTC, PandaHun reviewed
굳이 QueryDsl interface를 만들어서 Implementation Class를 만드는 이유는??
인터페이스를 구현해 추가할 여지의 요구사항이 생기지않는다면
그냥 Interface가 아니라 Class로 둬도 될거같은데?

2020-09-19 13:20 UTC, Livenow14 commented
이후 추가 용이성을 위해 놔둠
쿼리 메서드 분리 패턴을 적용시에 class를 둬도 괜찮을 듯

2020-09-27 02:50 UTC, PandaHun requested changes
id naming 명시부탁
그리고 pageDto 구조 설명 부탁, 속성도 몇개 사라짐

2020-09-27 02:50 UTC, PandaHun commented on src/main/java/org/greenbyme/angelhack/domain/personalmission/PersonalMissionQueryDslImpl.java
> +    public Page<PersonalMission> findAllByMissionId(Long id, Pageable pageable) {
missionId로 바꿔주세요

2020-09-27 02:50 UTC, PandaHun commented on src/main/java/org/greenbyme/angelhack/domain/personalmission/PersonalMissionQueryDslImpl.java
> +    public Optional<PersonalMission> findDetailsById(Long id) {
personalMissionId로 바꿔주세요

2020-09-27 02:50 UTC, PandaHun commented on src/main/java/org/greenbyme/angelhack/domain/personalmission/PersonalMissionQueryDslImpl.java
> +
무슨공백이죠?

2020-09-27 02:50 UTC, PandaHun commented on src/main/java/org/greenbyme/angelhack/domain/post/PostQueryDslImpl.java
> +
공백

2020-09-27 02:50 UTC, PandaHun commented on src/main/java/org/greenbyme/angelhack/domain/post/PostQueryDslImpl.java
> +    private BooleanExpression personMissionIdEq(Long id) {
무슨 id인가요?
아래도

2020-09-27 02:50 UTC, PandaHun commented on src/main/java/org/greenbyme/angelhack/domain/user/UserQueryDslImpl.java
> +    public Optional<User> findByIdFetch(Long id) {
id 명명해주세요

2020-09-27 02:50 UTC, PandaHun commented on src/main/java/org/greenbyme/angelhack/service/PageService.java
> +        List<PersonalMission> personalMissionAllByUserIdFetch = personalMissionRepository.findAllByUserIdFetch(userId);
네이밍이 너무 긴데
결국 personalMissionList아닌가요? userId fetch는 어차피 메소드에서 정해지는데...
고려할 필요가있을것같습니다. 메소드 호출같아요ㅕ

2020-09-27 02:50 UTC, PandaHun commented on src/main/java/org/greenbyme/angelhack/service/dto/page/HomePageDto.java
> +    UserHomePageDetailDto userHomePageDetailDto;
접근지정자는?
그리고 구조를 바꾼 이유는?

2020-09-27 02:50 UTC, PandaHun commented on src/main/java/org/greenbyme/angelhack/service/dto/page/HomePageDto.java
> -    private Long progressCampaign;
진행중갯수 속성 아예 사라졌는데? 확인바람

2020-09-27 13:51 UTC, Livenow14 commented on src/main/java/org/greenbyme/angelhack/domain/personalmission/PersonalMissionQueryDslImpl.java
> +    public Page<PersonalMission> findAllByMissionId(Long id, Pageable pageable) {
확인

2020-09-27 13:51 UTC, Livenow14 commented on src/main/java/org/greenbyme/angelhack/domain/personalmission/PersonalMissionQueryDslImpl.java
> +    public Optional<PersonalMission> findDetailsById(Long id) {
확인

2020-09-27 13:53 UTC, Livenow14 commented on src/main/java/org/greenbyme/angelhack/service/dto/page/HomePageDto.java
> -    private Long progressCampaign;
커밋 설명에 있듯 이후 추가예정

2020-09-27 14:05 UTC, Livenow14 commented on src/main/java/org/greenbyme/angelhack/domain/post/PostQueryDslImpl.java
> +    private BooleanExpression personMissionIdEq(Long id) {
이부분은 메소드 자체에 personalMissionIdEq라는 이름을 정해주고 있기때문에 안했음.
메서드에서 파라미터를 예상할 수 있을때 어떤 convention을 사요할지 정해야 할듯 
우선 변경함

2020-09-27 14:05 UTC, Livenow14 commented on src/main/java/org/greenbyme/angelhack/domain/user/UserQueryDslImpl.java
> +    public Optional<User> findByIdFetch(Long id) {
확인

2020-09-27 14:05 UTC, Livenow14 commented on src/main/java/org/greenbyme/angelhack/service/PageService.java
> +        List<PersonalMission> personalMissionAllByUserIdFetch = personalMissionRepository.findAllByUserIdFetch(userId);
확인

2020-09-27 14:05 UTC, Livenow14 commented on src/main/java/org/greenbyme/angelhack/service/dto/page/HomePageDto.java
> +    UserHomePageDetailDto userHomePageDetailDto;
구조를 바꾼 이유는, 
이전의 Dto에서 1 + N의 문제가 보였고,
HomePage의 확장성을 고려했을때 User만 따로 빼내어져 있는 것 보다, dto로 감싸서 보내는 것이 더 좋다고 판단함. 
접근지정자는 수정.

2020-09-27 14:07 UTC, Livenow14 commented on src/main/java/org/greenbyme/angelhack/service/dto/page/HomePageDto.java
> -    private Long progressCampaign;
이부분 회의때 얘기해봐야 할 것 같아서, 완료한 사람들 수로 바꿈. 
요구사항 정확히 해야할 필요있음.

2020-09-28 00:36 UTC, PandaHun commented on src/main/java/org/greenbyme/angelhack/service/dto/page/HomePageDto.java
> +    UserHomePageDetailDto userHomePageDetailDto;
확인

2020-09-28 00:37 UTC, PandaHun approved these changes
승인요

2020-09-28 13:46 UTC, merged